CoreAssociation_StudyList_WGS <- c("AsnicarF_2021", "BackhedF_2015", "Barton_et_al_2018", "BedarfJR_2017", "Bengtsson-PalmeJ_2015", "BritoIL_2016", "CosteaPI_2017", "Cronin_et_al_2018", "DeFilippisF_2019", "DhakanDB_2019", "FengQ_2015", "FerrettiP_2018", "Ghosh_et_al_2020", "HMP_2012", "HMP_2019_t2d", "HallAB_2017", "HanniganGD_2017", "HansenLBS_2018", "IjazUZ_2017", "Jeffery_et_al_2020", "JieZ_2017", "KarlssonFH_2013", "KaurK_2020", "KeohaneDM_2020", "LiJ_2014", "LiJ_2017", "LifeLinesDeep_2016", "LiuW_2016", "LokmerA_2019", "MehtaRS_2018", "MetaCardis_2020_a", "MobegiF_2020", "NagySzakalD_2017", "NielsenHB_2014", "Obregon-TitoAJ_2015", "PasolliE_2019", "PehrssonE_2016", "QinJ_2012", "QinN_2014", "RampelliS_2015", "RenallN_2023", "RubelMA_2020", "SankaranarayananK_2015", "SchirmerM_2016", "ShaoY_2019", "SmitsSA_2017", "TettAJ_2019_a", "TettAJ_2019_b", "TettAJ_2019_c", "ThomasAM_2018a", "ThomasAM_2018b", "ThomasAM_2019_c", "VogtmannE_2016", "WampachL_2018", "WirbelJ_2018", "XieH_2016", "YachidaS_2019", "YassourM_2016", "YassourM_2018", "YeZ_2018", "YuJ_2015", "ZeeviD_2015", "ZellerG_2014", "ZhuF_2020")

CoreAssociation_StudyList_16S <- c("AG", "Arivale", "CuestaZuluaga_et_al_2018", "He", "Kedia_et_al", "LogMPie", "MicroDiab_India", "Odamaki")

df_CombinedScores_WGS <- data.frame("CoreAssociation"=rank_scale(colSums(apply(prevalentDf_new[rownames(SpeciesScores_NEW),CoreAssociation_StudyList_WGS],1,function(x)(ifelse(x>=0.65,1,0))) * apply(r2Df_new[rownames(SpeciesScores_NEW),CoreAssociation_StudyList_WGS],1,function(x)(ifelse(x>=0.70,1,0))))),"StabilityAssociation"=((rank_scale1((-1) * sign(meta_WGS_Aitchison[rownames(SpeciesScores_NEW),"beta"]) * (-log(meta_WGS_Aitchison[rownames(SpeciesScores_NEW),"qval"],10)) * meta_WGS_Aitchison[rownames(SpeciesScores_NEW),"consistency"])) + (rank_scale1((-1) * sign(meta_WGS_BrayCurtis[rownames(SpeciesScores_NEW),"beta"]) * (-log(meta_WGS_BrayCurtis[rownames(SpeciesScores_NEW),"qval"],10)) * meta_WGS_BrayCurtis[rownames(SpeciesScores_NEW),"consistency"])))/2,"HealthAssociation"=df_HealthAssociation_WGS[rownames(SpeciesScores_NEW),1])

df_CombinedScores_WGS$HACKScore <- ifelse(is.nan(apply(apply(df_CombinedScores_WGS,2,rank_scale),1,function(x)(mean(x)*(1-Gini(x))))),0,apply(apply(df_CombinedScores_WGS,2,rank_scale),1,function(x)(mean(x)*(1-Gini(x)))))

df_CombinedScores_16S <- data.frame("CoreAssociation"=rank_scale(colSums(apply(prevalentDf_new[rownames(SpeciesScores_NEW),CoreAssociation_StudyList_16S],1,function(x)(ifelse(x>=0.65,1,0))) * apply(r2Df_new[rownames(SpeciesScores_NEW),CoreAssociation_StudyList_16S],1,function(x)(ifelse(x>=0.70,1,0))))),"StabilityAssociation"=((rank_scale1((-1) * sign(meta_16S_Aitchison[rownames(SpeciesScores_NEW),"beta"]) * (-log(meta_16S_Aitchison[rownames(SpeciesScores_NEW),"qval"],10)) * meta_16S_Aitchison[rownames(SpeciesScores_NEW),"consistency"])) + (rank_scale1((-1) * sign(meta_16S_BrayCurtis[rownames(SpeciesScores_NEW),"beta"]) * (-log(meta_16S_BrayCurtis[rownames(SpeciesScores_NEW),"qval"],10)) * meta_16S_BrayCurtis[rownames(SpeciesScores_NEW),"consistency"])))/2,"HealthAssociation"=df_HealthAssociation_16S[rownames(SpeciesScores_NEW),1],row.names=rownames(SpeciesScores_NEW))

df_CombinedScores_16S <- as.data.frame(apply(df_CombinedScores_16S,2,function(x)(ifelse(is.na(x),0,x))))

df_CombinedScores_16S$HACKScore <- ifelse(is.nan(apply(apply(df_CombinedScores_16S,2,rank_scale),1,function(x)(mean(x)*(1-Gini(x))))),0,apply(apply(df_CombinedScores_16S,2,rank_scale),1,function(x)(mean(x)*(1-Gini(x)))))

TaxaDetection <- read.table("G:\\My Drive\\Lab\\Projects\\CoreFinder\\Manuscript\\Analysis_Data\\HACK_Index_Reproducibility\\Taxa_Detection.txt",sep="\t",row.names=1,header=TRUE)